### PR TITLE
Changed the title in index.html

### LINKED ISSUE #21: bug: Update the index.html file
change 
```html
<title>Vite + React</title>
```
to
```html
<title>Upto Skills</title>
```

### PR DESCRIPTION
**Pull request by devansh-dek**
Fixes #21 
Changed the title in index.html file

### CODE REVIEW

**Review by vaibhavvatsbhartiya — COMMENTED** [review]
It is good if you can use uptoskills logo too. 
On line 6: change vite.svg img to uptoskills logo of svg file.

**Comment by devansh-dek** [comment]
On it.

**Comment by devansh-dek** [comment]
Where can i get upstoskills logo svg?

**Comment by vaibhavvatsbhartiya** [comment]
> Where can i get upstoskills logo svg?

so you can find it on google or create one using canva. but make sure logo used is in the assets folder with other images files only. Don't place it any where in the code.

https://github.com/code-Atish/codeEditor/tree/main/src/assets 
i share location for the images with you.

**Pull request merged**
